### ISSUE TITLE
Question about  filters in the Conv2D class

### ISSUE THREAD

**Issue by jesusmontera** [GiacomoPorpiglia/CNN-from-scratch#27]
Hello, I'm trying to use your CNN for chess position classification. You describe the Conv2D filters size as CNNSize = [[6, 5], [16, 5]] and also 2  combinationMaps that I think contains indexs. Since my inputs are 8x8 instead of 28x28, I don't know what criteria you use to describe those indexs, and why those  combinationMaps doesn't match the size 5. This is my first look to a CNN, Thanks for the code.

**Comment by GiacomoPorpiglia** [comment]
Hello, I'm happy to help you! The CNNSize contains 2 arrays, one for each convLayer. For example the first one ( [6, 5] ) is saying that the first convolutional layer has 6 kernels with dimension 5x5. The second layer has 16 kernels, also 5x5.
The combination maps instead contain the indeces of the outputs of the previous layer that are NOT taken as input by each kernel of the convLayer. So, the first combinationMap (combinationMap) refers to the first convLayer, which has as input the original image. Since we have only one input, each kernel takes that as input, and so the combinationMap0 has empty  lists inside, meaning there's nothing we don't want to take (so we want to take all the inputs, in this case only the original image).
For the second convLayer, the input is more complex, because the previous convLayer has created 6 "images", which now act as input for the second convLayer. Each of its kernel takes as input the sum of a combination of the 6 inputs. For example by looking at combinationMap1, we see the first entry is [3, 4, 5]: this means the first of the 16 kernels in the second convLayer will take as inputs the sum of all 6 previous outputs (the "images" created by the first conv layer), EXCEPT 3, 4 and 5.

I hope it's clearer now how everything works. For your case, it probably doesn't make much sense to use convolutional layer on 8x8 images, because they are very small. However, if you want to, I'd probably reduce the kernel size to 3, since 5 is too big in my opinion.

**Comment by jesusmontera** [comment]
Thanks, I think I will make my inputs as yours 28x28 size by adding other chess futures like attack, square control, castlings etc, so I wont need to change the combinations. Since my input are in the range -1 to 1 this will work ok with your activation  functions because your inputs are in the range 0 to 1?. Also you have 10 expected_outputs categories, and I have 1001 from stockfish engine evaluation. In yours images the same numbers are similar, so input have correlation with output, but in chess different positions may have the same evaluation. I don't know if  a CNN can deal with that. I've tried with a BPN from FANN but is to slow for training.

**Comment by GiacomoPorpiglia** [comment]
For what you want to do, I would actually not recommend this at all. This is becaues my model is specifically built for images, which have their own characteristics and dependencies, which cannot be easily translated to the ones of a chess position. I have experience with Neural Nets in chess engines (I have my own chess engine here on github btw), and they use far more sophisticated approaches. With what you want to try, I'm afraid you wouldn't go very far. I encourage you to explore NNUEs, and if you want to build a strong engine, use a proper trainer with GPU acceleration (like the stockfish one, based on PyTorch).
